/**
 * @module modals/course-capability-modal
 * @description Interactive diagnostic reporting modal for probing Canvas REST API permissions
 * and exporting structured Markdown diagnostics reports.
 */

import { App, Modal, Notice, Setting, normalizePath } from "obsidian";
import type CanvasSyncBridgePlugin from "../main";
import type { CanvasCourseSummary, CourseCapabilityReport, DataCategoryCapability } from "../types";

/**
 * Generates a structured Markdown diagnostic report from a CourseCapabilityReport object.
 */
export function generateCapabilityMarkdownReport(report: CourseCapabilityReport): string {
  const lines: string[] = [
    "# Canvas Course Capability Diagnostic Report",
    "",
    `- **Course:** ${report.courseName} (ID: \`${report.courseId}\`)`,
    `- **Tested At:** ${report.testedAt}`,
    `- **Generated By:** Obsidian Canvas Sync`,
    "",
    "| Data Category | Status | Endpoint | Details |",
    "| :--- | :--- | :--- | :--- |"
  ];

  for (const cap of Object.values(report.capabilities)) {
    let statusEmoji = "🟢 Available";
    if (cap.status === "restricted") statusEmoji = "🔒 Restricted";
    else if (cap.status === "empty") statusEmoji = "⚪ Empty";
    else if (cap.status === "unsupported") statusEmoji = "⚠️ Unsupported";
    else if (cap.status === "error") statusEmoji = "❌ Error";

    const detailText = cap.status === "available"
      ? (cap.count !== undefined ? `${cap.count} item(s) found` : "Available (200 OK)")
      : (cap.errorMessage || `HTTP ${cap.statusCode ?? "N/A"}`);

    lines.push(`| **${cap.label}** | ${statusEmoji} | \`${cap.endpoint}\` | ${detailText.replace(/\|/g, "\\|")} |`);
  }

  lines.push(
    "",
    "## Summary & Status Legend",
    "",
    "- **🟢 Available**: Endpoint returned HTTP 200 with accessible data.",
    "- **🔒 Restricted**: Access is restricted or unauthorized by Canvas permission policies (HTTP 401/403).",
    "- **⚪ Empty**: Endpoint is accessible, but currently contains 0 items.",
    "- **⚠️ Unsupported**: Endpoint is disabled or unsupported on this Canvas instance (HTTP 404/501).",
    "- **❌ Error**: A network or server error occurred while testing the endpoint."
  );

  return lines.join("\n");
}

/**
 * Diagnostic modal allowing users to probe Canvas API permissions across endpoints and export reports.
 */
export class CourseCapabilityModal extends Modal {
  private plugin: CanvasSyncBridgePlugin;
  private preselectedCourseId?: string | number;
  private courses: CanvasCourseSummary[] = [];
  private selectedCourseId: string | number | null = null;
  private lastReport: CourseCapabilityReport | null = null;
  private isProbing = false;

  constructor(app: App, plugin: CanvasSyncBridgePlugin, preselectedCourseId?: string | number) {
    super(app);
    this.plugin = plugin;
    this.preselectedCourseId = preselectedCourseId;
  }

  async onOpen(): Promise<void> {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("canvas-capability-modal");

    contentEl.createEl("h2", { text: "Canvas Course Capability Diagnostics" });

    if (!this.plugin.getSettings().canvasBaseUrl || !this.plugin.getSettings().canvasApiToken) {
      contentEl.createEl("p", {
        text: "Please configure your Canvas Base URL and API Token in settings before running diagnostics.",
        cls: "canvas-sync-error"
      });
      new Setting(contentEl).addButton((btn) => btn.setButtonText("Close").setCta().onClick(() => this.close()));
      return;
    }

    const loadingEl = contentEl.createDiv("canvas-diagnostics-loading");
    loadingEl.createSpan({ text: "Loading courses..." });

    try {
      this.courses = await this.plugin.getApiClient().listCourses({ includeInactive: true });
      loadingEl.remove();

      if (this.courses.length === 0) {
        contentEl.createEl("p", { text: "No courses found on Canvas.", cls: "canvas-no-courses" });
        return;
      }

      if (this.preselectedCourseId) {
        this.selectedCourseId = this.preselectedCourseId;
      } else {
        this.selectedCourseId = this.courses[0].id;
      }

      this.renderControls();

      if (this.selectedCourseId) {
        await this.runProbe(this.selectedCourseId);
      }
    } catch (err) {
      loadingEl.remove();
      const msg = err instanceof Error ? err.message : String(err);
      contentEl.createEl("p", { text: `Failed to load courses: ${msg}`, cls: "canvas-sync-error" });
    }
  }

  onClose(): void {
    const { contentEl } = this;
    contentEl.empty();
  }

  private renderControls(): void {
    const { contentEl } = this;

    const controlRow = contentEl.createDiv("canvas-capability-controls");
    const setting = new Setting(controlRow)
      .setName("Select course to test")
      .setDesc("Probes each data category to verify Canvas REST API permissions.");

    setting.addDropdown((dropdown) => {
      for (const course of this.courses) {
        dropdown.addOption(String(course.id), `${course.name} (${course.course_code || course.id})`);
      }
      if (this.selectedCourseId) {
        dropdown.setValue(String(this.selectedCourseId));
      }
      dropdown.onChange((val) => {
        this.selectedCourseId = val;
      });
    });

    setting.addButton((btn) =>
      btn
        .setButtonText("Run Diagnostic Probe")
        .setCta()
        .onClick(() => {
          if (this.selectedCourseId) {
            void this.runProbe(this.selectedCourseId);
          }
        })
    );
  }

  private async runProbe(courseId: string | number): Promise<void> {
    if (this.isProbing) return;
    this.isProbing = true;

    const { contentEl } = this;

    let resultsEl = contentEl.querySelector(".canvas-capability-results-wrapper") as HTMLElement;
    if (!resultsEl) {
      resultsEl = contentEl.createDiv("canvas-capability-results-wrapper");
    }
    resultsEl.empty();

    const loading = resultsEl.createDiv("canvas-diagnostics-loading");
    loading.createSpan({ text: "⏳ Probing Canvas endpoints (this may take a few seconds)..." });

    try {
      const client = this.plugin.getApiClient();
      this.lastReport = await client.probeCourseCapabilities(courseId);
      this.isProbing = false;
      this.renderReport(resultsEl, this.lastReport);
    } catch (err) {
      this.isProbing = false;
      loading.empty();
      const msg = err instanceof Error ? err.message : String(err);
      resultsEl.createDiv({ text: `Diagnostic probe failed: ${msg}`, cls: "canvas-status-error" });
    }
  }

  private renderReport(container: HTMLElement, report: CourseCapabilityReport): void {
    container.empty();

    const header = container.createDiv("canvas-report-header");
    header.createEl("h3", { text: `Report: ${report.courseName}` });
    header.createEl("p", { text: `Course ID: ${report.courseId} • Tested at: ${new Date(report.testedAt).toLocaleString()}`, cls: "canvas-meta-item" });

    const tableWrap = container.createDiv("canvas-diagnostics-table-wrap");
    const table = tableWrap.createEl("table", { cls: "canvas-diagnostics-table" });

    const thead = table.createEl("thead");
    const trHead = thead.createEl("tr");
    trHead.createEl("th", { text: "Data Category" });
    trHead.createEl("th", { text: "Status" });
    trHead.createEl("th", { text: "HTTP / Count" });
    trHead.createEl("th", { text: "Endpoint" });
    trHead.createEl("th", { text: "Details" });

    const tbody = table.createEl("tbody");
    for (const cap of Object.values(report.capabilities)) {
      const tr = tbody.createEl("tr");
      tr.createEl("td", { text: cap.label, cls: "canvas-diag-cat" });

      const statusTd = tr.createEl("td", { cls: "canvas-diag-status" });
      const badge = statusTd.createSpan({ cls: `canvas-badge-diag canvas-badge-${cap.status}` });
      badge.setText(
        cap.status === "available"
          ? "🟢 Available"
          : cap.status === "restricted"
            ? "🔒 Restricted"
            : cap.status === "empty"
              ? "⚪ Empty"
              : cap.status === "unsupported"
                ? "⚠️ Unsupported"
                : "❌ Error"
      );

      const countTd = tr.createEl("td", { cls: "canvas-diag-count" });
      if (cap.status === "available") {
        countTd.setText(cap.count !== undefined ? `${cap.count} item(s)` : "200 OK");
      } else {
        countTd.setText(`HTTP ${cap.statusCode ?? "N/A"}`);
      }

      tr.createEl("td", { cls: "canvas-diag-endpoint" }).createEl("code", { text: cap.endpoint });
      tr.createEl("td", { cls: "canvas-diag-details", text: cap.errorMessage || "-" });
    }

    // Actions
    const actions = container.createDiv("canvas-capability-actions");
    const copyBtn = actions.createEl("button", { text: "📋 Copy Markdown Report" });
    copyBtn.addEventListener("click", () => {
      const md = generateCapabilityMarkdownReport(report);
      void navigator.clipboard.writeText(md).then(() => {
        new Notice("Diagnostic markdown report copied to clipboard!");
      });
    });

    const saveVaultBtn = actions.createEl("button", { text: "💾 Save Report to Vault", cls: "mod-cta" });
    saveVaultBtn.addEventListener("click", () => {
      void (async () => {
        const md = generateCapabilityMarkdownReport(report);
        const folder = this.plugin.getSettings().rootFolder || "Canvas";
        const filename = `Diagnostics - ${report.courseName.replace(/[\\/:*?"<>|]/g, "-")}.md`;
        const path = normalizePath(`${folder}/${filename}`);
        try {
          await this.plugin.upsertFile(path, md, false);
          new Notice(`Diagnostic report saved to ${path}!`);
        } catch (e) {
          const msg = e instanceof Error ? e.message : String(e);
          new Notice(`Failed to save report: ${msg}`);
        }
      })();
    });
  }
}
