import { App, Modal, Notice, Setting, normalizePath } from "obsidian";
import type CanvasSyncBridgePlugin from "./main";
import type { CanvasCourseSummary, CourseCapabilityReport, DataCategoryCapability } from "./types";

export function generateCapabilityMarkdownReport(report: CourseCapabilityReport): string {
  const lines: string[] = [
    "# Canvas Course Capability Diagnostic Report",
    "",
    `- **Course:** ${report.courseName} (ID: \`${report.courseId}\`)`,
    `- **Tested At:** ${report.testedAt}`,
    `- **Generated By:** Obsidian Canvas Sync`,
    "",
    "| Data Category | Status | Endpoint | Details |",
    "| :--- | :--- | :--- | :--- |"
  ];

  for (const cap of Object.values(report.capabilities)) {
    let statusEmoji = "🟢 Available";
    if (cap.status === "restricted") statusEmoji = "🔒 Restricted";
    else if (cap.status === "empty") statusEmoji = "⚪ Empty";
    else if (cap.status === "unsupported") statusEmoji = "⚠️ Unsupported";
    else if (cap.status === "error") statusEmoji = "❌ Error";

    const detailText = cap.status === "available"
      ? (cap.count !== undefined ? `${cap.count} item(s) found` : "Available (200 OK)")
      : (cap.errorMessage || `HTTP ${cap.statusCode ?? "N/A"}`);

    lines.push(`| **${cap.label}** | ${statusEmoji} | \`${cap.endpoint}\` | ${detailText.replace(/\|/g, "\\|")} |`);
  }

  lines.push(
    "",
    "## Summary & Status Legend",
    "",
    "- **🟢 Available**: Endpoint returned HTTP 200 with accessible data.",
    "- **🔒 Restricted**: Access is restricted or unauthorized by Canvas permission policies (HTTP 401/403).",
    "- **⚪ Empty**: Endpoint is accessible, but currently contains 0 items.",
    "- **⚠️ Unsupported**: Endpoint is disabled or unsupported on this Canvas instance (HTTP 404/501).",
    "- **❌ Error**: A network or server error occurred while testing the endpoint."
  );

  return lines.join("\n");
}

export class CourseCapabilityModal extends Modal {
  private plugin: CanvasSyncBridgePlugin;
  private preselectedCourseId?: string | number;
  private courses: CanvasCourseSummary[] = [];
  private selectedCourseId: string | number | null = null;
  private lastReport: CourseCapabilityReport | null = null;
  private isProbing = false;

  constructor(app: App, plugin: CanvasSyncBridgePlugin, preselectedCourseId?: string | number) {
    super(app);
    this.plugin = plugin;
    this.preselectedCourseId = preselectedCourseId;
  }

  async onOpen(): Promise<void> {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("canvas-diagnostics-modal");

    contentEl.createEl("h2", { text: "🔍 Course capability & permission diagnostics" });
    contentEl.createEl("p", {
      text: "Probe Canvas course API endpoints to check permissions, inspect active data types, and identify restricted features.",
      cls: "canvas-diagnostics-desc"
    });

    const controlsContainer = contentEl.createDiv("canvas-diagnostics-controls");
    const resultsContainer = contentEl.createDiv("canvas-diagnostics-results");

    await this.renderControls(controlsContainer, resultsContainer);

    if (this.preselectedCourseId) {
      this.selectedCourseId = this.preselectedCourseId;
      await this.runProbe(this.selectedCourseId, resultsContainer);
    }
  }

  onClose(): void {
    const { contentEl } = this;
    contentEl.empty();
  }

  private async renderControls(controlsEl: HTMLElement, resultsEl: HTMLElement): Promise<void> {
    controlsEl.empty();

    const client = this.plugin.getApiClient();
    const settings = this.plugin.getSettings();

    if (!settings.canvasBaseUrl || !settings.canvasApiToken) {
      controlsEl.createDiv({
        cls: "canvas-status-error",
        text: "⚠️ Canvas base URL and API token must be configured in settings to run capability diagnostics."
      });
      return;
    }

    try {
      this.courses = await client.listCourses({ includeInactive: true });
    } catch (err) {
      controlsEl.createDiv({
        cls: "canvas-status-error",
        text: `Failed to load courses: ${err instanceof Error ? err.message : String(err)}`
      });
      return;
    }

    if (this.courses.length === 0) {
      controlsEl.createDiv({
        cls: "canvas-no-courses",
        text: "No courses found on Canvas account."
      });
      return;
    }

    if (!this.selectedCourseId && this.courses.length > 0) {
      this.selectedCourseId = this.courses[0].id;
    }

    new Setting(controlsEl)
      .setName("Select course")
      .setDesc("Choose the course to probe for API permissions and data availability.")
      .addDropdown((dropdown) => {
        for (const c of this.courses) {
          dropdown.addOption(String(c.id), `${c.name} (${c.course_code || c.id})`);
        }
        if (this.selectedCourseId) {
          dropdown.setValue(String(this.selectedCourseId));
        }
        dropdown.onChange((val) => {
          this.selectedCourseId = val;
        });
      })
      .addButton((btn) => {
        btn
          .setButtonText("Run Capability Probe")
          .setCta()
          .onClick(async () => {
            if (!this.selectedCourseId) return;
            await this.runProbe(this.selectedCourseId, resultsEl);
          });
      });
  }

  public async runProbe(courseId: string | number, resultsEl: HTMLElement): Promise<void> {
    if (this.isProbing) return;
    this.isProbing = true;
    resultsEl.empty();

    const loadingDiv = resultsEl.createDiv("canvas-diagnostics-loading");
    loadingDiv.createSpan({ text: "⏳ Probing course API endpoints (Modules, Pages, Assignments, Grades, Files, etc.)..." });

    try {
      const client = this.plugin.getApiClient();
      const report = await client.probeCourseCapabilities(courseId);
      this.lastReport = report;
      this.renderResults(resultsEl, report);
    } catch (err) {
      resultsEl.empty();
      resultsEl.createDiv({
        cls: "canvas-status-error",
        text: `Error during capability probe: ${err instanceof Error ? err.message : String(err)}`
      });
    } finally {
      this.isProbing = false;
    }
  }

  private renderResults(resultsEl: HTMLElement, report: CourseCapabilityReport): void {
    resultsEl.empty();

    const header = resultsEl.createDiv("canvas-diagnostics-summary");
    header.createEl("h3", { text: `Report: ${report.courseName}` });
    const meta = header.createEl("p", { cls: "canvas-course-subtext" });
    meta.createSpan({ text: `Course ID: ${report.courseId} • Tested at: ${new Date(report.testedAt).toLocaleString()}` });

    const tableWrap = resultsEl.createDiv("canvas-diagnostics-table-wrap");
    const table = tableWrap.createEl("table", { cls: "canvas-diagnostics-table" });

    const thead = table.createEl("thead");
    const trHead = thead.createEl("tr");
    trHead.createEl("th", { text: "Data Category" });
    trHead.createEl("th", { text: "Status" });
    trHead.createEl("th", { text: "Endpoint" });
    trHead.createEl("th", { text: "Details" });

    const tbody = table.createEl("tbody");
    for (const cap of Object.values(report.capabilities)) {
      const row = tbody.createEl("tr");

      // Category
      row.createEl("td", { text: cap.label, cls: "canvas-diag-cat" });

      // Badge
      const statusTd = row.createEl("td", { cls: "canvas-diag-status" });
      const badge = statusTd.createSpan({
        cls: `canvas-badge-diag canvas-badge-${cap.status}`
      });
      badge.setText(this.getStatusBadgeText(cap));

      // Endpoint
      const epTd = row.createEl("td", { cls: "canvas-diag-endpoint" });
      epTd.createEl("code", { text: cap.endpoint });

      // Details
      const detailsTd = row.createEl("td", { cls: "canvas-diag-details" });
      if (cap.status === "available") {
        detailsTd.setText(cap.count !== undefined ? `${cap.count} item(s) detected` : "Available (200 OK)");
      } else if (cap.status === "empty") {
        detailsTd.setText("No items found (0 items)");
      } else {
        detailsTd.setText(cap.errorMessage || `HTTP ${cap.statusCode ?? "N/A"}`);
      }
    }

    // Action buttons
    const actions = resultsEl.createDiv("canvas-diagnostics-actions");

    const copyBtn = actions.createEl("button", { text: "📋 Copy Markdown Report" });
    copyBtn.addEventListener("click", () => {
      const md = generateCapabilityMarkdownReport(report);
      void navigator.clipboard.writeText(md).then(() => {
        new Notice("Diagnostics report copied to clipboard!");
      });
    });

    const saveBtn = actions.createEl("button", { text: "💾 Save Report to Vault" });
    saveBtn.addEventListener("click", async () => {
      try {
        const md = generateCapabilityMarkdownReport(report);
        const settings = this.plugin.getSettings();
        const root = settings.rootFolder || "Canvas";
        const fileName = `Course-${report.courseId}-Capability-Report.md`;
        const path = normalizePath(`${root}/${fileName}`);
        await this.plugin.upsertFile(path, md + "\n", false);
        new Notice(`Saved report to ${path}`);
      } catch (e) {
        new Notice(`Failed to save report: ${e instanceof Error ? e.message : String(e)}`);
      }
    });

    const rerunBtn = actions.createEl("button", { text: "🔄 Re-run Probe" });
    rerunBtn.addEventListener("click", () => {
      void this.runProbe(report.courseId, resultsEl);
    });
  }

  private getStatusBadgeText(cap: DataCategoryCapability): string {
    switch (cap.status) {
      case "available":
        return "🟢 Available";
      case "restricted":
        return `🔒 Restricted (${cap.statusCode || 403})`;
      case "empty":
        return "⚪ Empty";
      case "unsupported":
        return `⚠️ Unsupported (${cap.statusCode || 404})`;
      case "error":
        return `❌ Error (${cap.statusCode || "Fail"})`;
      default:
        return cap.status;
    }
  }
}
